[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "bayesian_nbv"
version = "0.1.0"
requires-python = ">=3.9"
# pytorch3d is also required, but must be installed manually (see README)
dependencies = [
    "torch>=2.0",
    "numpy",
    "scipy",
    "PyYAML",
    "easydict",
    "tqdm",
    "matplotlib",
    "plotly",
    "trimesh",
    "point-cloud-utils",
    "gpytoolbox",
    "robust-laplacian",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["bayesian_nbv*"]
